Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.vitech.Handler
      CodeUri: /Users/bohdan.domalchuk/VITech/localstack/core-java
      Runtime: java17
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET: local-bucket
          LOCALSTACK_HOSTNAME: 172.17.0.2