spring:
  cloud:
    aws:
      region:
        static: us-east-2
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
        region: us-east-2
      sqs:
        endpoint: http://sqs.localhost.localstack.cloud:4566
        region: us-east-2
      dynamodb:
        endpoint: http://dynamodb.localhost.localstack.cloud:4566
        region: us-east-2
