name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  localstack:
    name: 'LocalStack'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.1.2
        with:
          image-tag: '2.2.0'
          install-awslocal: 'true'
          configuration: DEBUG=1

      - name: Create resources
        run: ./init-aws.sh
